default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres  
  password: 'postgres'
  host: localhost
  port: 5432

development:
  <<: *default
  database: vmaxnet_api_development

test:
  <<: *default
  database: vmaxnet_api_test

production:
  <<: *default
  database: vmaxnet_api_production
  username: vmaxnet_api
  password: <%= ENV["VMAXNET_API_DATABASE_PASSWORD"] %>